replicaCount: 2

image:
  repository: rubemmoreira/todo-app
  tag: 115ea0113c54743bc1413cefc1970c2eeeb5d921
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30902

ingress:
  enabled: false
  host: todo.local
  className: nginx

database:
  host: postgres.todo-app.svc.cluster.local
  port: 5432
  name: todos
  user: todoapp
  password: todo123

kafka:
  brokers: todo-kafka-kafka-bootstrap.kafka:9092

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi