replicaCount: 2

image:
  repository: rubemmoreira/todo-app
  tag: f4eb4511a645116bd61bbe5a108d5b542b7358b9
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30657

database:
  host: 192.168.3.37
  port: "5432"
  name: stocks
  user: stockuser
  password: stock123

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
